// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalTaxiService.Infrastructure.Postgres;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinimalTaxiService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(MinimalTaxiDbContext))]
    [Migration("20260325135226_AddLocalFromToAddresses")]
    partial class AddLocalFromToAddresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.DriverLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_driver_locations");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_locations_driver_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_driver_locations_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_driver_locations_timestamp");

                    b.ToTable("driver_locations", (string)null);
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.IntercityTripDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasColumnName("available_seats");

                    b.Property<DateTimeOffset?>("DepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at");

                    b.Property<Point>("From")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("from_location");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("from_address");

                    b.Property<int?>("RequiredSeats")
                        .HasColumnType("integer")
                        .HasColumnName("required_seats");

                    b.Property<Point>("To")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("to_location");

                    b.Property<string>("ToAddress")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("to_address");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_intercity_trip_details");

                    b.HasIndex("AvailableSeats")
                        .HasDatabaseName("ix_intercity_trip_details_available_seats");

                    b.HasIndex("DepartureAt")
                        .HasDatabaseName("ix_intercity_trip_details_departure_at");

                    b.HasIndex("From")
                        .HasDatabaseName("ix_intercity_trip_details_from_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("From"), "gist");

                    b.HasIndex("To")
                        .HasDatabaseName("ix_intercity_trip_details_to_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("To"), "gist");

                    b.HasIndex("TripId")
                        .IsUnique()
                        .HasDatabaseName("ux_intercity_trip_details_trip_id");

                    b.ToTable("intercity_trip_details", (string)null);
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.SavedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_locations");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_saved_locations_created_at");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_saved_locations_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_locations_user_id");

                    b.ToTable("saved_locations", (string)null);
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Point>("Destination")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("destination_location");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("from_address");

                    b.Property<Point>("Origin")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("origin_location");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("ToAddress")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("to_address");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_trips_created_at");

                    b.HasIndex("Destination")
                        .HasDatabaseName("ix_trips_destination_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Destination"), "gist");

                    b.HasIndex("Origin")
                        .HasDatabaseName("ix_trips_origin_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Origin"), "gist");

                    b.HasIndex("DriverId", "Status")
                        .HasDatabaseName("ix_trips_driver_id_status");

                    b.HasIndex("PassengerId", "Status")
                        .HasDatabaseName("ix_trips_passenger_id_status");

                    b.HasIndex("City", "Type", "Status")
                        .HasDatabaseName("ix_trips_city_type_status");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.TripParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BookedSeats")
                        .HasColumnType("integer")
                        .HasColumnName("booked_seats");

                    b.Property<string>("DropoffAddress")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("dropoff_address");

                    b.Property<Point>("DropoffLocation")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("dropoff_location");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("boolean")
                        .HasColumnName("is_driver");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("pickup_address");

                    b.Property<Point>("PickupLocation")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("pickup_location");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_participants");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_participants_trip_id");

                    b.HasIndex("TripId", "IsDriver")
                        .HasDatabaseName("ix_trip_participants_trip_id_is_driver");

                    b.HasIndex("TripId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_participants_trip_id_user_id");

                    b.ToTable("trip_participants", (string)null);
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_users_phone_number");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.TripParticipant", b =>
                {
                    b.HasOne("MinimalTaxiService.Domain.Entities.Trip", null)
                        .WithMany("Participants")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.User", b =>
                {
                    b.OwnsOne("MinimalTaxiService.Domain.ValueObjects.CarInfo", "CarInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("car_brand");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("car_color");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("car_model");

                            b1.Property<string>("PlateNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("car_plate_number");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MinimalTaxiService.Domain.ValueObjects.UserAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apartment")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("apartment");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("house");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("street");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");

                    b.Navigation("CarInfo");
                });

            modelBuilder.Entity("MinimalTaxiService.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
