export const CAR_MODELS_BY_BRAND = {
  Audi: ["A1", "A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8"],
  BMW: ["1 Series", "3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X6"],
  BYD: ["F3", "Song", "Tang", "Han", "Qin", "Dolphin"],
  Changan: ["CS35", "CS55", "CS75", "UNI-K", "UNI-T"],
  Chery: ["Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 8"],
  Chevrolet: ["Aveo", "Cruze", "Malibu", "Captiva", "Tahoe"],
  Citroen: ["C3", "C4", "C5", "Berlingo", "Jumpy"],
  Daewoo: ["Nexia", "Matiz", "Gentra", "Lanos"],
  Dodge: ["Charger", "Challenger", "Durango", "Journey"],
  Fiat: ["500", "Panda", "Tipo", "Doblo"],
  Ford: ["Focus", "Mondeo", "Kuga", "Explorer", "Transit"],
  Geely: ["Coolray", "Atlas", "Emgrand", "Monjaro"],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
  GreatWall: ["Hover H3", "Hover H5", "Poer"],
  Haval: ["Jolion", "F7", "F7x", "Dargo", "H9"],
  Honda: ["Civic", "Accord", "CR-V", "HR-V", "Pilot"],
  Hyundai: ["Solaris", "Elantra", "Sonata", "Tucson", "Santa Fe", "Creta"],
  Infiniti: ["Q50", "QX50", "QX60", "QX80"],
  Isuzu: ["D-Max", "MU-X", "N-Series"],
  Jaguar: ["XE", "XF", "F-Pace", "E-Pace", "I-Pace"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler"],
  Kia: ["Rio", "Ceed", "Cerato", "K5", "Sportage", "Sorento", "Carnival"],
  Lada: ["Granta", "Vesta", "Niva Legend", "Niva Travel", "Largus"],
  LandRover: [
    "Defender",
    "Discovery",
    "Range Rover",
    "Range Rover Sport",
    "Evoque",
  ],
  Lexus: ["IS", "ES", "RX", "NX", "LX", "GX"],
  Mazda: ["Mazda 2", "Mazda 3", "Mazda 6", "CX-5", "CX-9", "CX-30"],
  Mercedes: ["A-Class", "C-Class", "E-Class", "S-Class", "GLC", "GLE", "GLS"],
  Mini: ["Cooper", "Countryman", "Clubman"],
  Mitsubishi: ["Lancer", "ASX", "Outlander", "Pajero Sport", "L200"],
  Nissan: ["Almera", "Qashqai", "X-Trail", "Murano", "Patrol", "Terrano"],
  Opel: ["Astra", "Insignia", "Mokka", "Zafira"],
  Peugeot: ["208", "301", "308", "408", "3008", "5008"],
  Porsche: ["Macan", "Cayenne", "Panamera", "Taycan"],
  Renault: ["Logan", "Sandero", "Duster", "Kaptur", "Arkana"],
  Skoda: ["Rapid", "Octavia", "Superb", "Karoq", "Kodiaq"],
  Subaru: ["Impreza", "Legacy", "Forester", "Outback", "XV"],
  Suzuki: ["Swift", "Vitara", "SX4", "Jimny"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Toyota: ["Corolla", "Camry", "RAV4", "Land Cruiser", "Highlander", "Prius"],
  Volkswagen: ["Polo", "Golf", "Jetta", "Passat", "Tiguan", "Touareg"],
  Volvo: ["S60", "S90", "XC40", "XC60", "XC90"],
};

export const CAR_BRANDS = Object.keys(CAR_MODELS_BY_BRAND).sort((a, b) =>
  a.localeCompare(b),
);
